### ISSUE TITLE
help me with this error

### ISSUE THREAD

**Issue by euvii** [adamkhai08/Yokans#6]
DiscordAPIError[50035]: Invalid Form Body
3.options[3][UNION_TYPE_CHOICES]: Value of field "type" must be one of (7, 2, 1, 10, 6, 9, 4, 11, 8, 5, 3).
    at SequentialHandler.runRequest (/home/runner/Leoo/node_modules/@discordjs/rest/dist/index.js:667:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.queueRequest (/home/runner/Leoo/node_modules/@discordjs/rest/dist/index.js:464:14)
    at async REST.request (/home/runner/Leoo/node_modules/@discordjs/rest/dist/index.js:910:22) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ]
  },
  rawError: {
    code: 50035,
    errors: { '3': [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/1073267276180115480/guilds/1009800422099263529/commands'
}

**Comment by jerrybots123** [comment]
facing the same error what to do?
